services:
    _defaults:
        public: true

    bitbag.sylius_ing_pay_plugin.controller.notify_controller:
        class: BitBag\SyliusIngPayPlugin\Controller\NotifyController
        arguments:
            - '@sylius.repository.order'
            - '@sylius.repository.payment'
            - '@doctrine.orm.entity_manager'
            - '@bitbag.ing_pay_plugin.resolver.signature_resolver'
