services:
    bitbag.ing_pay_plugin.form.type.gateway_configuration.ing_pay_paywall:
        class: BitBag\SyliusIngPayPlugin\Form\Type\IngPayGatewayConfigurationType
        tags:
            - name: sylius.gateway_configuration_type
              type: ing_pay_paywall
              label: 'bitbag.ing_pay_plugin.paywall'
            - name: form.type
