services:
    bitbag.sylius_ing_pay_plugin.processor.payment_transition:
        class: BitBag\SyliusIngPayPlugin\Processor\PaymentTransitionProcessor
        arguments:
            - '@sylius_abstraction.state_machine'
