bitbag_sylius_ing_pay_payment_notify:
    path: /payment/ing_pay/notify
    methods: [POST]
    defaults:
        _controller: bitbag.sylius_ing_pay_plugin.controller.notify_controller::verifyIngPayNotification
